drop table foam_info;
drop table census_age;
drop table census_males;
drop table census_females;
drop table census_race;
drop table census_relationship;
drop table census_household;
drop table census_income;
drop view foam_analysis;

create table foam_info (
	foam_info_id serial primary key,
	survey_date date,
	address varchar(500),
	foam boolean,
	corridor varchar(200),
	census_tract numeric(5,2),
	geoid varchar(50)
);

create table census_age(
census_age_id serial primary key,
id1 varchar(50),
geoid varchar(50),
census_tract numeric(5,2),
total_population smallint,
years_lt_5 smallint,
years_5_9 smallint,
years_10_14 smallint,
years_15_19 smallint,
years_20_24 smallint,
years_25_29 smallint,
years_30_34 smallint,
years_35_39 smallint,
years_40_44 smallint,
years_45_49 smallint,
years_50_54 smallint,
years_55_59 smallint,
years_60_64 smallint,
years_65_69 smallint,
years_70_74 smallint,
years_75_79 smallint,
years_80_84 smallint,
years_gte_85 smallint,
total_pop_median_age numeric(3,1),
years_gte_16 smallint,
years_gte_18 smallint,
years_gte_21 smallint,
years_gte_62 smallint,
years_gte_65 smallint);

create table census_males(
census_males_id serial primary key,
id1 varchar(50),
geoid varchar(50),
census_tract numeric(5,2),
male_pop smallint,
males_lt_5 smallint,
males_5_9 smallint,
males_10_14 smallint,
males_15_19 smallint,
males_20_24 smallint,
males_25_29 smallint,
males_30_34 smallint,
males_35_39 smallint,
males_40_44 smallint,
males_45_49 smallint,
males_50_54 smallint,
males_55_59 smallint,
males_60_64 smallint,
males_65_69 smallint,
males_70_74 smallint,
males_75_79 smallint,
males_80_84 smallint,
males_gte_85 smallint,
male_median_age numeric(3,1),
males_gte_16 smallint,
males_gte_18 smallint,
males_gte_21 smallint,
males_gte_62 smallint,
males_get_65 smallint
);

create table census_females(
	census_females_id serial primary key,
	id1 varchar(50),
	geoid varchar(50),
	census_tract numeric(5,2),
	female_pop smallint,
	females_lt_5 smallint,
	females_5_9 smallint,
	females_10_14 smallint,
	females_15_19 smallint,
	females_20_24 smallint,
	females_25_29 smallint,
	females_30_34 smallint,
	females_35_39 smallint,
	females_40_44 smallint,
	females_45_49 smallint,
	females_50_54 smallint,
	females_55_59 smallint,
	females_60_64 smallint,
	females_65_69 smallint,
	females_70_74 smallint,
	females_75_79 smallint,
	females_80_84 smallint,
	females_gte_85 smallint,
	female_median_age numeric(3,1),
	females_gte_16 smallint,
	females_gte_18 smallint,
	females_gte_21 smallint,
	females_gte_62 smallint,
	females_get_65 smallint
);

create table census_race(
	census_race_id serial primary key,
	id1 varchar(50),
	geoid varchar(50),
	census_tract numeric(5,2),
	total_pop_race smallint,
	total_pop_one_race smallint,
	race_white smallint,
	race_african_american smallint,
	race_american_indian smallint,
	race_asian smallint,
	race_asian_indian smallint,
	race_asian_chinese smallint,
	race_asian_filipino smallint,
	race_asian_japanese smallint,
	race_asian_korean smallint,
	race_asian_vietnamese smallint,
	race_asian_other smallint,
	race_pacific_island smallint,
	race_native_hawaiian smallint,
	race_guamanian smallint,
	race_samoan smallint,
	race_other_pac_isl smallint,
	race_other smallint,
	total_pop_multi_race smallint,
	multi_race_white smallint,
	multi_race_asian smallint,
	multi_race_african_american smallint,
	multi_race_other smallint,
	total_pop_hispanic_latino smallint,
	race_hispanic_latino smallint,
	race_mexican smallint,
	race_puerto_rican smallint,
	race_cuban smallint,
	race_other_hisp_latino smallint,
	race_hisp_l_not_hisp_l smallint
);

create table census_relationship(
	census_relationship_id serial primary key,
	id1 varchar(50),
	geoid varchar(50),
	census_tract numeric(5,2),
	rel_total_pop smallint,
	rel_pop_in_households smallint,
	rel_householder smallint,
	rel_spouse smallint,
	rel_child smallint,
	rel_own_child_lt_18 smallint,
	rel_other_rel smallint,
	rel_other_rel_lt_18 smallint,
	rel_other_rel_gte_65 smallint,
	rel_non_rel smallint,
	rel_non_rel_lt_18 smallint,
	rel_non_rel_gte_65 smallint,
	rel_non_rel_unmarried_partner smallint,
	rel_group smallint,
	rel_group_institutionalized smallint,
	rel_group_inst_male smallint,
	rel_group_inst_female smallint,
	rel_group_non_inst smallint,
	rel_group_non_inst_male smallint,
	rel_group_non_inst_female smallint
);

create table census_household(
	census_household_id serial primary key,
	id1 varchar(50),
	geoid varchar(50),
	census_tract numeric(5,2),
	total_households smallint,
	family_households smallint,
	family_own_children_lt_18 smallint,
	family_husb_wife smallint,
	family_husb_wife_own_children smallint,
	family_male_only smallint,
	family_male_only_children_lt_18 smallint,
	family_female_only smallint,
	family_female_only_children_lt_18 smallint,
	non_family smallint,
	householder_only smallint,
	householder_only_male smallint,
	hh_only_male_gte_65 smallint,
	householder_only_female smallint,
	hh_only_female_gte_65 smallint,
	hh_lt_18 smallint,
	hh_gte_65 smallint,
	average_household_size numeric(4,2),
	average_family_size numeric(4,2),
	total_housing_units smallint,
	tot_occupied_housing_units smallint,
	vacant_housing_units smallint,
	vacant_housing_for_rent smallint,
	vacant_rented_unoccupied smallint,
	vacant_housing_for_sale smallint,
	vacant_sold_unoccupied smallint,
	vacant_seasonal smallint,
	vacant_other smallint,
	vacancy_rate numeric(3,1),
	rental_vacancy_rate numeric(3,1),
	occupied_housing_units smallint,
	owner_occupied_housing smallint,
	pop_in_owner_occ_units smallint,
	avg_size_owner_occ_units numeric(4,2),
	renter_occupied_housing smallint,
	pop_in_renter_occ_units smallint,
	avg_size_renter_occ_units numeric(4,2)
);

create table census_income(
	census_income_id serial primary key,
	census_tract numeric(5,2),
	geoid varchar(50),
	population smallint,
	hispanic_population smallint,
	white_population smallint,
	fagi_total_2010 numeric(12,2),
	fagi_median_2010 numeric(8,2),
	fagi_total_2013 numeric(12,2),
	fagi_median_2013 numeric(8,2)
);

create or replace view foam_analysis as
	select
	f.*,
	i.fagi_total_2010,
	i.fagi_median_2010,
	i.fagi_total_2013,
	i.fagi_median_2013,
	case when i.white_population * 2 > i.population then 1 else 0 end as majority_white
	from foam_info f, census_income i
	where f.geoid = i.geoid;
